apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: bXlkYg==
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: bXl1c2VycGFzc3dvcmQ=
