apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.common.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.common.selectorLabel}}
  ports:
    - port: {{ .Values.todoapp.clusterIP.port}}
      targetPort: {{ .Values.todoapp.clusterIP.targetPort}}
