apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.common.namespace}}
  labels:
    app: {{ .Values.common.appLabel }}
spec:
  strategy:
    type: {{ .Values.todoapp.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.todoapp.strategy.rollingUpdate.maxUnavailable}}
      maxSurge: {{ .Values.todoapp.strategy.rollingUpdate.maxSurge }}
  replicas: {{ .Values.todoapp.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.common.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.common.appLabel }}
    spec:
      containers:
        - name: {{ .Values.todoapp.containerName }}
          image: {{ .Values.todoapp.image.repository }}:{{ .Values.todoapp.image.tag }}
          imagePullPolicy: {{ .Values.todoapp.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Chart.Name }}-storage
              mountPath: /app/data
            - name: {{ .Chart.Name }}-secret
              mountPath: /app/secrets
              readOnly: true
            - name: {{ .Chart.Name }}-config
              mountPath: /app/config
              readOnly: true
          resources:
            requests:
              memory: {{ .Values.todoapp.resources.requests.memory }}
              cpu: {{ .Values.todoapp.resources.requests.cpu }}
            limits:
              memory: {{ .Values.todoapp.resources.limits.memory}}
              cpu: {{ .Values.todoapp.resources.limits.cpu }}
          envFrom:
            - configMapRef:
                name: {{ .Values.todoapp.env.configMap }}
            - secretRef:
                name: {{ .Values.todoapp.env.secrets }}
          ports:
            - containerPort: {{ .Values.todoapp.containerPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.todoapp.livenessProbe.httpGet.path}}
              port: {{ .Values.todoapp.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.todoapp.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.todoapp.livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              path: {{ .Values.todoapp.readinessProbe.httpGet.path }}
              port: {{ .Values.todoapp.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.todoapp.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.todoapp.readinessProbe.periodSeconds }}
      volumes:
        - name: {{ .Chart.Name }}-storage
          persistentVolumeClaim:
            claimName: {{ .Values.todoapp.pvc.name }}
        - name: {{ .Chart.Name }}-secret
          secret:
            secretName: {{ .Chart.Name }}-secret
        - name: {{ .Chart.Name }}-config
          configMap:
            name: {{ .Chart.Name }}-config
