apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.common.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: todoapp.local
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ .Chart.Name }}-service
              port:
                number: 80