apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.todoapp.pvc.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  volumeName: {{ .Values.todoapp.pv.name }}
  accessModes:
    {{- toYaml .Values.todoapp.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.todoapp.pvc.resources.requests.storage }}
