apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secret
  namespace: todoapp
type: Opaque
data:
  DB_USER: bXl1c2Vy
  DB_PASSWORD: bXl1c2VycGFzc3dvcmQ=
  SECRET_KEY: MiE1Z20rXzIjJGkweTNibWk9cmlxdV9saTd2OTBuKWRAeW9wal8qJjQ2dXc9MGhhZm4=