name: Helm-CI

on:
  workflow_run:
    workflows: ["App-CI"]
    types: ["completed"]
    branches: ["develop"]
  pull_request:
    branches: ["main"]


permissions:
  contents: read


env:
  CHART_PATH: ./aws-pet-project-charts/todoapp
  APP_NS: todoapp

jobs:
  helm-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm Chart
        run: helm package ${{ env.CHART_PATH }} -d ./artifacts

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.repository_owner }} --password-stdin


      - name: Push Helm Chart
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          FILE=$(ls ./artifacts/*.tgz | head -n1)
          GITHUB_USER_LOWER=$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')
          echo "Pushing $FILE to oci://ghcr.io/$GITHUB_USER_LOWER/charts"
          helm push $FILE oci://ghcr.io/$GITHUB_USER_LOWER/charts



      - name: Lint Helm Chart
        run: helm lint ${{ env.CHART_PATH }}


      - name: Render chart
        run: helm template test "${CHART_PATH}" >/dev/null

