name: Main-CI

run-name: ${{ github.actor }} - ${{ github.ref_name}} -${{ github.sha }}

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  PythonVersion: 3.11
  DockerImageName: aws-pet-project

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PythonVersion }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort pytest pytest-django

      - name: Run linters
        run: |
          flake8 . --extend-ignore=E203,E501,W503
          black .
          black --check .
          isort --check-only .

      - name: Run tests
        run: |
          python manage.py test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: .

  docker-ci:
    needs: python-ci
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-artifacts

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile
          load: true
          tags: ${{ env.DockerImageName }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: image
          image-ref: ${{ env.DockerImageName }}:sha-${{ github.sha }}
          vuln-type: 'os,library'
          format: 'table'
          severity: 'CRITICAL'
          ignore-unfixed: true
          exit-code: '1'

      - name: Docker Push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: ${{ env.DockerImageName }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max